export const userTableData = [
    {
        "isClient": 0,
        "userId": "b/bb",
        "userName": "abcrain",
        "name": "abc",
        "createdOn": 1721023571,
        "goldenTicket": 0,
        "parentId": 0,
        "email": "raininfotech07@gmail.com",
        "sponsorId": 0,
        "sponserName": "-",
        "staterKit": 0,
        "phoneNumber": "+20 4545454545555",
        "USDBalance": 0,
        "PPROBalance": 0,
        "tradeLastLoginIp": null,
        "tradeLastLoginTime": 0,
        "countryCode": "+20",
        "isActive": 1,
        "isVerify": 1,
        "walletAddress": null,
        "num": 1,
        "isLifeTime": 0,
        "subscriptionName": "Free",
        "referralCode": "-"
    },
    {
        "isClient": 0,
        "userId": "Zvs=",
        "userName": "sdssd",
        "name": "abcd",
        "createdOn": 1660367713,
        "goldenTicket": 0,
        "parentId": 0,
        "email": "dsdsasas@gmail.com",
        "sponsorId": 0,
        "sponserName": "-",
        "staterKit": 0,
        "phoneNumber": "+43 6503372543",
        "USDBalance": 0,
        "PPROBalance": 0,
        "tradeLastLoginIp": null,
        "tradeLastLoginTime": 0,
        "countryCode": "+43",
        "isActive": 0,
        "isVerify": 0,
        "walletAddress": null,
        "num": 2,
        "isLifeTime": 0,
        "subscriptionName": "Free",
        "referralCode": "-"
    },
    {
        "isClient": 0,
        "userId": "b/Pc",
        "userName": "acdac",
        "name": "abcd",
        "createdOn": 1669271992,
        "goldenTicket": 0,
        "parentId": 0,
        "email": "abcs@gmail.com",
        "sponsorId": 0,
        "sponserName": "-",
        "staterKit": 0,
        "phoneNumber": "+43 6503372543",
        "USDBalance": 0,
        "PPROBalance": 0,
        "tradeLastLoginIp": "127.0.0.1",
        "tradeLastLoginTime": 1669272395,
        "countryCode": "+43",
        "isActive": 1,
        "isVerify": 1,
        "walletAddress": null,
        "num": 3,
        "isLifeTime": 0,
        "subscriptionName": "Free",
        "referralCode": "-"
    },
    {
        "isClient": 0,
        "userId": "aPA=",
        "userName": "abcdaaa",
        "name": "abcd",
        "createdOn": 1656656037,
        "goldenTicket": 0,
        "parentId": 0,
        "email": "abcde@gmail.com",
        "sponsorId": 1,
        "sponserName": "auser",
        "staterKit": 0,
        "phoneNumber": "+43 5646575675",
        "USDBalance": 1722.19,
        "PPROBalance": 250,
        "tradeLastLoginIp": "127.0.0.1",
        "tradeLastLoginTime": 1691818811,
        "countryCode": "+43",
        "isActive": 1,
        "isVerify": 1,
        "walletAddress": null,
        "num": 4,
        "isLifeTime": 0,
        "subscriptionName": "Free",
        "referralCode": "6ARA2Z"
    },
    {
        "isClient": 0,
        "userId": "Z/U=",
        "userName": "abcd123",
        "name": "abcd",
        "createdOn": 1668485610,
        "goldenTicket": 0,
        "parentId": 0,
        "email": "abcdf@gmail.com",
        "sponsorId": 0,
        "sponserName": "-",
        "staterKit": 0,
        "phoneNumber": "+43 6767667776",
        "USDBalance": 0,
        "PPROBalance": 0,
        "tradeLastLoginIp": null,
        "tradeLastLoginTime": 0,
        "countryCode": "+43",
        "isActive": 1,
        "isVerify": 1,
        "walletAddress": null,
        "num": 5,
        "isLifeTime": 0,
        "subscriptionName": "Free",
        "referralCode": "-"
    },
    {
        "isClient": 0,
        "userId": "aPo=",
        "userName": "test123",
        "name": "abcd test",
        "createdOn": 1659422414,
        "goldenTicket": 0,
        "parentId": 0,
        "email": "tradetest@gmail.com",
        "sponsorId": 66,
        "sponserName": "tradethree1",
        "staterKit": 1,
        "phoneNumber": "+43 5656565656565656",
        "USDBalance": 763.26,
        "PPROBalance": 250,
        "tradeLastLoginIp": "127.0.0.1",
        "tradeLastLoginTime": 1677046686,
        "countryCode": "+43",
        "isActive": 1,
        "isVerify": 1,
        "walletAddress": null,
        "num": 6,
        "isLifeTime": 0,
        "subscriptionName": "Free",
        "referralCode": "UEYENG"
    },
    {
        "isClient": 0,
        "userId": "b/Dc",
        "userName": "teqst11",
        "name": "acdcd",
        "createdOn": 1684388786,
        "goldenTicket": 0,
        "parentId": 0,
        "email": "tes1qt1@gmail.com",
        "sponsorId": 0,
        "sponserName": "-",
        "staterKit": 0,
        "phoneNumber": "+12 565656565656",
        "USDBalance": 0,
        "PPROBalance": 0,
        "tradeLastLoginIp": null,
        "tradeLastLoginTime": 0,
        "countryCode": "+12",
        "isActive": 0,
        "isVerify": 0,
        "walletAddress": null,
        "num": 7,
        "isLifeTime": 0,
        "subscriptionName": "Free",
        "referralCode": "-"
    },
    {
        "isClient": 0,
        "userId": "b/Dd",
        "userName": "teqs1t11",
        "name": "acdcd",
        "createdOn": 1684388810,
        "goldenTicket": 0,
        "parentId": 0,
        "email": "tes11qt1@gmail.com",
        "sponsorId": 0,
        "sponserName": "-",
        "staterKit": 0,
        "phoneNumber": "+12 565656565656",
        "USDBalance": 11,
        "PPROBalance": 0,
        "tradeLastLoginIp": null,
        "tradeLastLoginTime": 0,
        "countryCode": "+12",
        "isActive": 0,
        "isVerify": 0,
        "walletAddress": null,
        "num": 8,
        "isLifeTime": 0,
        "subscriptionName": "Free",
        "referralCode": "-"
    },
    {
        "isClient": 0,
        "userId": "b/De",
        "userName": "test1",
        "name": "acdcd",
        "createdOn": 1684388703,
        "goldenTicket": 0,
        "parentId": 0,
        "email": "test1@gmail.com",
        "sponsorId": 0,
        "sponserName": "-",
        "staterKit": 0,
        "phoneNumber": "+12 565656565656",
        "USDBalance": 0,
        "PPROBalance": 0,
        "tradeLastLoginIp": null,
        "tradeLastLoginTime": 0,
        "countryCode": "+12",
        "isActive": 0,
        "isVerify": 0,
        "walletAddress": null,
        "num": 9,
        "isLifeTime": 0,
        "subscriptionName": "Free",
        "referralCode": "-"
    },
    {
        "isClient": 0,
        "userId": "b/Hf",
        "userName": "sdsd1",
        "name": "acssd",
        "createdOn": 1671697318,
        "goldenTicket": 0,
        "parentId": 0,
        "email": "dddddeee@gmail.com",
        "sponsorId": 0,
        "sponserName": "-",
        "staterKit": 0,
        "phoneNumber": "+43 5646575675",
        "USDBalance": 0,
        "PPROBalance": 0,
        "tradeLastLoginIp": null,
        "tradeLastLoginTime": 0,
        "countryCode": "+43",
        "isActive": 0,
        "isVerify": 0,
        "walletAddress": null,
        "num": 10,
        "isLifeTime": 0,
        "subscriptionName": "Free",
        "referralCode": "-"
    }
]