import Script from "next/script";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html
      lang="en"
      className="light-style layout-navbar-fixed layout-menu-fixed layout-compact"
      dir="ltr"
      data-theme="theme-default"
      data-assets-path="/assets/"
      data-template="vertical-menu-template"
      data-style="light">
      <head> 
 

         {/* <!-- Fonts --> */}
       <link
          href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&ampdisplay=swap"
          rel="stylesheet" />

        {/* <!-- Icons --> */}
        <link rel="stylesheet" href="/assets/vendor/fonts/fontawesome.css" />
        <link rel="stylesheet" href="/assets/vendor/fonts/tabler-icons.css" />
        <link rel="stylesheet" href="/assets/vendor/fonts/flag-icons.css" />

        {/* <!-- Core CSS --> */}

         <link rel="stylesheet" href="/assets/css/demo.css" />

        {/* <!-- Vendors CSS --> */}
        <link rel="stylesheet" href="/assets/vendor/libs/node-waves/node-waves.css" />

        <link rel="stylesheet" href="/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />
        <link rel="stylesheet" href="/assets/vendor/libs/typeahead-js/typeahead.css" />
        <link rel="stylesheet" href="/assets/vendor/libs/apex-charts/apex-charts.css" />
        <link rel="stylesheet" href="/assets/vendor/libs/datatables-bs5/datatables.bootstrap5.css" />
        <link rel="stylesheet" href="/assets/vendor/libs/datatables-responsive-bs5/responsive.bootstrap5.css" />
        <link rel="stylesheet" href="/assets/vendor/libs/datatables-buttons-bs5/buttons.bootstrap5.css" />

        {/* <!-- Page CSS --> */}

        {/* <!-- Helpers --> */}
        <Script src="/assets/vendor/js/helpers.js"></Script>
        {/* <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section --> */}

        {/* <!--? Template customizer: To hide customizer set displayCustomizer value false in config.js.  --> */}
        <Script src="/assets/vendor/js/template-customizer.js"></Script>

        {/* <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  --> */}
        <Script src="/assets/js/config.js"></Script>
      </head>

      <body>
        {children}
        {/* <!-- / Layout wrapper --> */}

        {/* <!-- Core JS --> */}
        {/* <!-- build:js assets/vendor/js/core.js --> */}

        <Script src="/assets/vendor/libs/jquery/jquery.js"></Script>
        <Script src="/assets/vendor/libs/popper/popper.js"></Script>
        <Script src="/assets/vendor/js/bootstrap.js"></Script>
        <Script src="/assets/vendor/libs/node-waves/node-waves.js"></Script>
        <Script src="/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></Script>
        <Script src="/assets/vendor/libs/hammer/hammer.js"></Script>
        <Script src="/assets/vendor/libs/i18n/i18n.js"></Script>
        <Script src="/assets/vendor/libs/typeahead-js/typeahead.js"></Script>
        <Script src="/assets/vendor/js/menu.js"></Script>

        {/* <!-- endbuild --> */}

        {/* <!-- Vendors JS --> */}
        <Script src="/assets/vendor/libs/apex-charts/apexcharts.js"></Script>
        <Script src="/assets/vendor/libs/datatables-bs5/datatables-bootstrap5.js"></Script>

        {/* <!-- Main JS --> */}
        <Script src="/assets/js/main.js"></Script>

        {/* <!-- Page JS --> */}
        <Script src="/assets/js/app-ecommerce-dashboard.js"></Script>
      </body>
    </html>
  );
}
