 
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
    lang="en"
    className="light-style layout-wide customizer-hide"
    dir="ltr"
    data-theme="theme-default"
    data-assets-path="/assets/"
    data-template="vertical-menu-template"
    data-style="light">
    <head>
      <meta charSet="utf-8" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
  
      <title>Vuexy - Bootstrap Admin Template</title>
  
      <meta name="description" content="" />
  
      {/* <!-- Favicon --> */}
      <link rel="icon" type="image/x-icon" href="/assets/img/favicon/favicon.ico" />
  
      {/* <!-- Fonts --> */}
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
      <link
        href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&ampdisplay=swap"
        rel="stylesheet" />
 
  
      {/* <!-- Core CSS --> */}
  
      <link rel="stylesheet" href="/assets/vendor/css/rtl/core.css" className="template-customizer-core-css" />
      <link rel="stylesheet" href="/assets/vendor/css/rtl/theme-default.css" className="template-customizer-theme-css" /> 
  
      {/* <!-- Page CSS --> */} 
      <link rel="stylesheet" href="/assets/vendor/css/pages/page-auth.css" />
 
    </head>
  
    <body> 
        {children} 
 
  </body>
</html>
  );
}
